export enum Sites {
  SITE = 'Site:',
  SITES = 'Sites',
  GENERAL = 'General',
  CONTACK_INFO = 'Contact Info',
  SETTINGS = 'Settings',
  DOCUMENTS = 'Documents',
  ASSETS = 'Assets',
  ASSET = 'Asset:',
  PERSONNEL = 'Personnel',
  PERSON = 'Person:',
  WORK_ORDER = 'Work Orders',
  WORK_ESTIMATES = 'Work Estimates',
  SHIFTS = 'Shifts',
  LABOR_RATES = 'Labor Rates',
  FEES = 'Fees',
  FEE = 'Fee:',
  OTHER_COSTS = 'Other Costs',
  OTHER_COST = 'Other Cost:',
  TAXES = 'Taxes',
  TAX = 'Tax:',
  VENDOR_STORES = 'Vendor Stores',
  PART_STOREROOMS = 'Part Storerooms'
}
