export enum Reports {
  ASSET_ANALYTICS = 'Asset Analytics',
  ASSET_PM_STATUS = 'Asset PM Status',
  AUDITING_EVENTS = 'Auditing Events',
  GENERAL_ACCOUNTING = 'General Accounting',
  HISTORICAL_INVENTORY_VALUATION = 'Historical Inventory Valuation',
  PART_RECEIPT_HISTORY = 'Part Receipt History',
  PART_USAGE_HISTORY = 'Part Usage History',
  PARTS_BEING_RETURNED = 'Parts Being Returned',
  PARTS_ON_ORDER = 'Parts on Order',
  PARTS_OVER_MAXIMUM_STOCKING_LEVEL = 'Parts Over Maximum',
  PARTS_UNDER_MINIMUM_STOCKING_LEVEL = 'Parts Under Minimum',
  PERMITS = 'Permits',
  PERSONNEL_ANALYTICS = 'Personnel Analytics',
  PM_COMPLIANCE = 'PM Compliance',
  PM_DETAIL_STATUS = 'PM Detail Status',
  SEARCH_AND_SELECT_QUERIES = 'Search and Select Queries',
  WASTE_AND_RECYCLING_GENERAL_ACCOUNTING = 'Waste & Recycling General Accounting',
  WORK_ORDER_HISTORY = 'Work Order History',
  WORK_REQUEST_ANALYTICS = 'Work Request Analytics',
  ASSET = 'Asset:',
  AUDITING_EVENT = 'Auditing Event',
  PART = 'Part:',
  PART_ON_HAND = 'Part on Hand',
  PURCHASE_RETURN_PART = 'Purchase Return Part',
  QUERY = 'Query:'
}
